# Reto Integrador - Unidad 1

# PARTE 2. SQL para Exploración de Datos (Data Discovery)

## - Se importan las librerías

In [7]:
import pandas as pd
from sqlalchemy import create_engine

## - Se carga el dataset

In [8]:
df = pd.read_csv(
    "../data/ventas_techventas_limpio.csv",
    encoding="latin-1"
)

df.head(60)

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lï¿½ï¿½
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15,25.0,0.00,Carlos Ruiz
2,1003,2024-01-10,C003,DataSolutions,Centro,Monitor 27,Electronica,5,350.0,0.05,Ana Lï¿½ï¿½
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3,1200.0,0.15,Carlos Ruiz
5,1006,2024-01-18,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres
6,1007,2024-01-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.05,Ana Lï¿½ï¿½
7,1008,2024-01-22,C006,NetPrime,Norte,Router WiFi 6,Redes,8,120.0,0.00,Luis Mora
8,1009,2024-01-25,C003,DataSolutions,Centro,SSD 1TB,Almacenamiento,12,95.0,0.10,Maria Torres
9,1010,2024-01-28,C007,AlphaTech,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Carlos Ruiz
10,1011,2024-02-02,C001,TechCorp SA,Norte,Monitor 27,Electronica,4,350.0,0.05,Ana Lï¿½ï¿½
11,1012,2024-02-05,C008,BetaSoft,Centro,Mouse Inalambrico,Perifericos,30,25.0,0.05,Maria Torres
12,1013,2024-02-08,C004,CloudNet,Este,Teclado Mecanico,Perifericos,5,85.0,0.00,Luis Mora
13,1014,2024-02-10,C009,GammaDevs,Oeste,Router WiFi 6,Redes,3,120.0,0.00,Carlos Ruiz
14,1015,2024-02-12,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,25,95.0,0.10,Maria Torres
15,1016,2024-02-15,C010,DeltaOps,Norte,Laptop Pro 15,Electronica,2,1200.0,0.20,Ana Lï¿½ï¿½
16,1017,2024-02-18,C006,NetPrime,Norte,Monitor 27,Electronica,6,350.0,0.05,Luis Mora
17,1018,2024-02-20,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz
18,1019,2024-02-22,C007,AlphaTech,Sur,Mouse Inalambrico,Perifericos,12,25.0,0.00,Maria Torres
19,1020,2024-02-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lï¿½ï¿½
20,1021,2024-03-01,C008,BetaSoft,Centro,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora
21,1022,2024-03-04,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,30,95.0,0.15,Carlos Ruiz
22,1023,2024-03-07,C009,GammaDevs,Oeste,Teclado Mecanico,Perifericos,8,85.0,0.00,Maria Torres
23,1024,2024-03-10,C010,DeltaOps,Norte,Monitor 27,Electronica,3,350.0,0.05,Ana Lï¿½ï¿½
24,1025,2024-03-12,C004,CloudNet,Este,Laptop Pro 15,Electronica,4,1200.0,0.10,Luis Mora
25,1026,2024-03-15,C005,Sistemas Globales,Oeste,Mouse Inalambrico,Perifericos,20,25.0,0.00,Carlos Ruiz
26,1027,2024-03-18,C006,NetPrime,Norte,SSD 1TB,Almacenamiento,15,95.0,0.00,Maria Torres
27,1028,2024-03-20,C007,AlphaTech,Sur,Router WiFi 6,Redes,6,120.0,0.10,Ana Lï¿½ï¿½
28,1029,2024-03-22,C002,Innovatek,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Luis Mora
29,1030,2024-03-25,C008,BetaSoft,Centro,Teclado Mecanico,Perifericos,10,85.0,0.05,Carlos Ruiz
30,1031,2024-03-28,C003,DataSolutions,Centro,Monitor 27,Electronica,3,350.0,0.05,Maria Torres
31,1032,2024-04-02,C009,GammaDevs,Oeste,SSD 1TB,Almacenamiento,22,95.0,0.10,Ana Lï¿½ï¿½
32,1033,2024-04-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,5,1200.0,0.15,Luis Mora
33,1034,2024-04-08,C010,DeltaOps,Norte,Mouse Inalambrico,Perifericos,25,25.0,0.00,Carlos Ruiz
34,1035,2024-04-10,C004,CloudNet,Este,Router WiFi 6,Redes,2,120.0,0.00,Maria Torres
35,1036,2024-04-12,C005,Sistemas Globales,Oeste,Monitor 27,Electronica,4,350.0,0.05,Ana Lï¿½ï¿½
36,1037,2024-04-15,C006,NetPrime,Norte,Teclado Mecanico,Perifericos,12,85.0,0.10,Luis Mora
37,1038,2024-04-18,C007,AlphaTech,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz
38,1039,2024-04-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.00,Maria Torres
39,1040,2024-04-22,C008,BetaSoft,Centro,Laptop Pro 15,Electronica,3,1200.0,0.10,Ana Lï¿½ï¿½
40,1041,2024-04-25,C009,GammaDevs,Oeste,Mouse Inalambrico,Perifericos,15,25.0,0.00,Luis Mora
41,1042,2024-04-28,C003,DataSolutions,Centro,Router WiFi 6,Redes,5,120.0,0.05,Carlos Ruiz
42,1043,2024-05-01,C010,DeltaOps,Norte,NaN,Electronica,2,350.0,0.05,Maria Torres
43,1044,2024-05-04,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,3,1200.0,0.20,Ana Lï¿½ï¿½
44,1045,2024-05-07,C004,CloudNet,Este,SSD 1TB,Almacenamiento,20,95.0,0.10,Luis Mora
45,1046,2024-05-10,C005,Sistemas Globales,Oeste,Teclado Mecanico,Perifericos,6,85.0,0.00,Carlos Ruiz
46,1047,2024-05-12,C006,NetPrime,Norte,Mouse Inalambrico,Perifericos,18,25.0,0.00,Maria Torres
47,1048,2024-05-15,C007,AlphaTech,Sur,Laptop Pro 15,Electronica,-1,1200.0,0.00,Ana Lï¿½ï¿½
48,1049,2024-05-18,C002,Innovatek,Sur,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora
49,1050,2024-05-20,C008,BetaSoft,Centro,SSD 1TB,Almacenamiento,25,95.0,0.15,Carlos Ruiz
50,1051,2024-05-22,C009,GammaDevs,Oeste,Monitor 27,Electronica,3,350.0,0.05,Maria Torres
51,1052,2024-05-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.00,Ana Lï¿½ï¿½
52,1053,2024-05-28,C010,DeltaOps,Norte,Mouse Inalambrico,Perifericos,20,25.0,0.00,Luis Mora
53,1054,2024-06-01,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,35,95.0,0.20,Carlos Ruiz
54,1055,2024-06-04,C004,CloudNet,Este,Monitor 27,Electronica,5,350.0,0.05,Maria Torres
55,1056,2024-06-07,C005,Sistemas Globales,Oeste,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lï¿½ï¿½
56,1057,2024-06-10,C006,NetPrime,Norte,Router WiFi 6,Redes,7,120.0,0.00,Luis Mora
57,1058,2024-06-12,C007,AlphaTech,Sur,Teclado Mecanico,Perifericos,9,85.0,0.05,Carlos Ruiz
58,1059,2024-06-15,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres
59,1060,2024-06-18,C008,BetaSoft,Centro,Monitor 27,Electronica,4,350.0,0.10,Ana Lï¿½ï¿½

## - Se crea la base de datos SQLite

In [4]:
engine = create_engine("sqlite:///../output/techventas.db")

## - Se Exporta el DataFrame a SQLite

In [5]:
df.to_sql(
    "ventas",
    con=engine,
    if_exists="replace",
    index=False
)

60

## - Se Verifica que se creó correctamente

In [6]:
pd.read_sql(
    "SELECT * FROM ventas LIMIT 5;",
    engine
)

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lï¿½ï¿½
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15,25.0,0.00,Carlos Ruiz
2,1003,2024-01-10,C003,DataSolutions,Centro,Monitor 27,Electronica,5,350.0,0.05,Ana Lï¿½ï¿½
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3,1200.0,0.15,Carlos Ruiz

## - Se crea la tabla vendedores para el JOIN

In [13]:
vendedores = pd.DataFrame({
    "vendedor": [
        "Ana Lopez",
        "Carlos Ruiz",
        "Luis Mora",
        "Maria Torres"
    ],
    "zona": [
        "Norte",
        "Sur",
        "Norte",
        "Centro"
    ],
    "meta_mensual": [
        8000,
        7500,
        8000,
        7000
    ]
})

- se guarda la tabla

In [14]:
vendedores.to_sql(
    "vendedores",
    con=engine,
    if_exists="replace",
    index=False
)

4

- Se verifica la creación de la tabla

In [15]:

pd.read_sql(
    "SELECT * FROM vendedores;",
    engine
)

       vendedor    zona  meta_mensual
0     Ana Lopez   Norte          8000
1   Carlos Ruiz     Sur          7500
2     Luis Mora   Norte          8000
3  Maria Torres  Centro          7000

## Consulta 1. Productos diferentes vendidos

In [24]:
consulta1 = """
SELECT DISTINCT producto
FROM ventas;
"""

pd.read_sql(consulta1, engine)

            producto
0      Laptop Pro 15
1  Mouse Inalambrico
2         Monitor 27
3   Teclado Mecanico
4            SSD 1TB
5      Router WiFi 6
6                NaN

####  Interpretación: Esta consulta permite identificar todos los productos diferentes que se encuentran registrados en el conjunto de datos.

## Consulta 2. Ventas realizadas entre enero y marzo

In [17]:
consulta2 = """
SELECT *
FROM ventas
WHERE fecha BETWEEN '2024-01-01' AND '2024-03-31';
"""

pd.read_sql(consulta2, engine)

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lï¿½ï¿½
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15,25.0,0.00,Carlos Ruiz
2,1003,2024-01-10,C003,DataSolutions,Centro,Monitor 27,Electronica,5,350.0,0.05,Ana Lï¿½ï¿½
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3,1200.0,0.15,Carlos Ruiz
5,1006,2024-01-18,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres
6,1007,2024-01-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.05,Ana Lï¿½ï¿½
7,1008,2024-01-22,C006,NetPrime,Norte,Router WiFi 6,Redes,8,120.0,0.00,Luis Mora
8,1009,2024-01-25,C003,DataSolutions,Centro,SSD 1TB,Almacenamiento,12,95.0,0.10,Maria Torres
9,1010,2024-01-28,C007,AlphaTech,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Carlos Ruiz
10,1011,2024-02-02,C001,TechCorp SA,Norte,Monitor 27,Electronica,4,350.0,0.05,Ana Lï¿½ï¿½
11,1012,2024-02-05,C008,BetaSoft,Centro,Mouse Inalambrico,Perifericos,30,25.0,0.05,Maria Torres
12,1013,2024-02-08,C004,CloudNet,Este,Teclado Mecanico,Perifericos,5,85.0,0.00,Luis Mora
13,1014,2024-02-10,C009,GammaDevs,Oeste,Router WiFi 6,Redes,3,120.0,0.00,Carlos Ruiz
14,1015,2024-02-12,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,25,95.0,0.10,Maria Torres
15,1016,2024-02-15,C010,DeltaOps,Norte,Laptop Pro 15,Electronica,2,1200.0,0.20,Ana Lï¿½ï¿½
16,1017,2024-02-18,C006,NetPrime,Norte,Monitor 27,Electronica,6,350.0,0.05,Luis Mora
17,1018,2024-02-20,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz
18,1019,2024-02-22,C007,AlphaTech,Sur,Mouse Inalambrico,Perifericos,12,25.0,0.00,Maria Torres
19,1020,2024-02-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lï¿½ï¿½
20,1021,2024-03-01,C008,BetaSoft,Centro,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora
21,1022,2024-03-04,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,30,95.0,0.15,Carlos Ruiz
22,1023,2024-03-07,C009,GammaDevs,Oeste,Teclado Mecanico,Perifericos,8,85.0,0.00,Maria Torres
23,1024,2024-03-10,C010,DeltaOps,Norte,Monitor 27,Electronica,3,350.0,0.05,Ana Lï¿½ï¿½
24,1025,2024-03-12,C004,CloudNet,Este,Laptop Pro 15,Electronica,4,1200.0,0.10,Luis Mora
25,1026,2024-03-15,C005,Sistemas Globales,Oeste,Mouse Inalambrico,Perifericos,20,25.0,0.00,Carlos Ruiz
26,1027,2024-03-18,C006,NetPrime,Norte,SSD 1TB,Almacenamiento,15,95.0,0.00,Maria Torres
27,1028,2024-03-20,C007,AlphaTech,Sur,Router WiFi 6,Redes,6,120.0,0.10,Ana Lï¿½ï¿½
28,1029,2024-03-22,C002,Innovatek,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Luis Mora
29,1030,2024-03-25,C008,BetaSoft,Centro,Teclado Mecanico,Perifericos,10,85.0,0.05,Carlos Ruiz
30,1031,2024-03-28,C003,DataSolutions,Centro,Monitor 27,Electronica,3,350.0,0.05,Maria Torres

#### Interpretación: Se muestran únicamente las ventas realizadas entre el 1 de enero y el 31 de marzo de 2024.

## Consulta 3. Total de ventas por región

In [18]:
consulta3 = """
SELECT
    region,
    SUM(cantidad * precio_unitario) AS total_vendido
FROM ventas
GROUP BY region
HAVING total_vendido > 5000;
"""

pd.read_sql(consulta3, engine)

   region  total_vendido
0  Centro        18795.0
1    Este        12715.0
2   Norte        32495.0
3   Oeste        13640.0
4     Sur        10560.0

#### Interpretación: Se calcula el total vendido por cada región y solo se muestran aquellas cuyo valor supera los 5000.

## Consulta 4. Estadísticas por categoría

In [19]:
consulta4 = """
SELECT
    categoria,
    COUNT(*) AS numero_ventas,
    SUM(cantidad) AS total_unidades,
    AVG(precio_unitario) AS precio_promedio
FROM ventas
GROUP BY categoria;
"""

pd.read_sql(consulta4, engine)

        categoria  numero_ventas  total_unidades  precio_promedio
0  Almacenamiento             12             260             95.0
1     Electronica             25              72            792.0
2     Perifericos             15             215             53.0
3           Redes              8              39            120.0

#### Interpretación: Se obtiene un resumen por categoría con el número de ventas, la cantidad total de unidades vendidas y el precio promedio.

## Consulta 5. Información de vendedores

In [20]:
consulta5 = """
SELECT
    v.order_id,
    v.vendedor,
    ven.zona,
    ven.meta_mensual
FROM ventas v
INNER JOIN vendedores ven
ON v.vendedor = ven.vendedor;
"""

pd.read_sql(consulta5, engine)

    order_id      vendedor    zona  meta_mensual
0       1002   Carlos Ruiz     Sur          7500
1       1004     Luis Mora   Norte          8000
2       1005   Carlos Ruiz     Sur          7500
3       1006  Maria Torres  Centro          7000
4       1008     Luis Mora   Norte          8000
5       1009  Maria Torres  Centro          7000
6       1010   Carlos Ruiz     Sur          7500
7       1012  Maria Torres  Centro          7000
8       1013     Luis Mora   Norte          8000
9       1014   Carlos Ruiz     Sur          7500
10      1015  Maria Torres  Centro          7000
11      1017     Luis Mora   Norte          8000
12      1018   Carlos Ruiz     Sur          7500
13      1019  Maria Torres  Centro          7000
14      1021     Luis Mora   Norte          8000
15      1022   Carlos Ruiz     Sur          7500
16      1023  Maria Torres  Centro          7000
17      1025     Luis Mora   Norte          8000
18      1026   Carlos Ruiz     Sur          7500
19      1027  Maria Torres  Centro          7000
20      1029     Luis Mora   Norte          8000
21      1030   Carlos Ruiz     Sur          7500
22      1031  Maria Torres  Centro          7000
23      1033     Luis Mora   Norte          8000
24      1034   Carlos Ruiz     Sur          7500
25      1035  Maria Torres  Centro          7000
26      1037     Luis Mora   Norte          8000
27      1038   Carlos Ruiz     Sur          7500
28      1039  Maria Torres  Centro          7000
29      1041     Luis Mora   Norte          8000
30      1042   Carlos Ruiz     Sur          7500
31      1043  Maria Torres  Centro          7000
32      1045     Luis Mora   Norte          8000
33      1046   Carlos Ruiz     Sur          7500
34      1047  Maria Torres  Centro          7000
35      1049     Luis Mora   Norte          8000
36      1050   Carlos Ruiz     Sur          7500
37      1051  Maria Torres  Centro          7000
38      1053     Luis Mora   Norte          8000
39      1054   Carlos Ruiz     Sur          7500
40      1055  Maria Torres  Centro          7000
41      1057     Luis Mora   Norte          8000
42      1058   Carlos Ruiz     Sur          7500
43      1059  Maria Torres  Centro          7000

#### Interpretación: El JOIN permite relacionar la información de las ventas con los datos de cada vendedor, como su zona y la meta mensual asignada.

## Consulta 6. Productos con precio superior al promedio

In [21]:
consulta6 = """
SELECT
    producto,
    precio_unitario
FROM ventas
WHERE precio_unitario >
(
    SELECT AVG(precio_unitario)
    FROM ventas
);
"""

pd.read_sql(consulta6, engine)

         producto  precio_unitario
0   Laptop Pro 15           1200.0
1   Laptop Pro 15           1200.0
2   Laptop Pro 15           1200.0
3   Laptop Pro 15           1200.0
4   Laptop Pro 15           1200.0
5   Laptop Pro 15           1200.0
6   Laptop Pro 15           1200.0
7   Laptop Pro 15           1200.0
8   Laptop Pro 15           1200.0
9   Laptop Pro 15           1200.0
10  Laptop Pro 15           1200.0
11  Laptop Pro 15           1200.0
12  Laptop Pro 15           1200.0

#### Interpretación: Se identifican los productos cuyo precio unitario es superior al promedio del catálogo.

## Conclusión

Con SQL fue posible explorar la información del conjunto de datos mediante consultas que permitieron filtrar registros, agrupar información, calcular estadísticas, relacionar tablas mediante JOIN y utilizar subconsultas. Estas herramientas facilitan el análisis de los datos y apoyan la toma de decisiones.