# Reto Integrador - Unidad 1

## Parte 3. Ingeniería de Datos con Pandas

En este notebook se realiza la carga, limpieza, transformación y exportación del conjunto de datos utilizando Pandas y SQLite.

## - Se Importan librerías

In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

## - Se carga el dataset

In [4]:
df = pd.read_csv(
    "../data/ventas_techventas_limpio.csv",
    encoding="latin-1",
    parse_dates=["fecha"]
)

df.head(60)

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lopez
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15,25.0,0.00,Carlos Ruiz
2,1003,2024-01-10,C003,DataSolutions,Centro,Monitor 27,Electronica,5,350.0,0.05,Ana Lopez
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3,1200.0,0.15,Carlos Ruiz
5,1006,2024-01-18,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres
6,1007,2024-01-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.05,Ana Lopez
7,1008,2024-01-22,C006,NetPrime,Norte,Router WiFi 6,Redes,8,120.0,0.00,Luis Mora
8,1009,2024-01-25,C003,DataSolutions,Centro,SSD 1TB,Almacenamiento,12,95.0,0.10,Maria Torres
9,1010,2024-01-28,C007,AlphaTech,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Carlos Ruiz
10,1011,2024-02-02,C001,TechCorp SA,Norte,Monitor 27,Electronica,4,350.0,0.05,Ana Lopez
11,1012,2024-02-05,C008,BetaSoft,Centro,Mouse Inalambrico,Perifericos,30,25.0,0.05,Maria Torres
12,1013,2024-02-08,C004,CloudNet,Este,Teclado Mecanico,Perifericos,5,85.0,0.00,Luis Mora
13,1014,2024-02-10,C009,GammaDevs,Oeste,Router WiFi 6,Redes,3,120.0,0.00,Carlos Ruiz
14,1015,2024-02-12,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,25,95.0,0.10,Maria Torres
15,1016,2024-02-15,C010,DeltaOps,Norte,Laptop Pro 15,Electronica,2,1200.0,0.20,Ana Lopez
16,1017,2024-02-18,C006,NetPrime,Norte,Monitor 27,Electronica,6,350.0,0.05,Luis Mora
17,1018,2024-02-20,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz
18,1019,2024-02-22,C007,AlphaTech,Sur,Mouse Inalambrico,Perifericos,12,25.0,0.00,Maria Torres
19,1020,2024-02-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lopez
20,1021,2024-03-01,C008,BetaSoft,Centro,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora
21,1022,2024-03-04,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,30,95.0,0.15,Carlos Ruiz
22,1023,2024-03-07,C009,GammaDevs,Oeste,Teclado Mecanico,Perifericos,8,85.0,0.00,Maria Torres
23,1024,2024-03-10,C010,DeltaOps,Norte,Monitor 27,Electronica,3,350.0,0.05,Ana Lopez
24,1025,2024-03-12,C004,CloudNet,Este,Laptop Pro 15,Electronica,4,1200.0,0.10,Luis Mora
25,1026,2024-03-15,C005,Sistemas Globales,Oeste,Mouse Inalambrico,Perifericos,20,25.0,0.00,Carlos Ruiz
26,1027,2024-03-18,C006,NetPrime,Norte,SSD 1TB,Almacenamiento,15,95.0,0.00,Maria Torres
27,1028,2024-03-20,C007,AlphaTech,Sur,Router WiFi 6,Redes,6,120.0,0.10,Ana Lopez
28,1029,2024-03-22,C002,Innovatek,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Luis Mora
29,1030,2024-03-25,C008,BetaSoft,Centro,Teclado Mecanico,Perifericos,10,85.0,0.05,Carlos Ruiz
30,1031,2024-03-28,C003,DataSolutions,Centro,Monitor 27,Electronica,3,350.0,0.05,Maria Torres
31,1032,2024-04-02,C009,GammaDevs,Oeste,SSD 1TB,Almacenamiento,22,95.0,0.10,Ana Lopez
32,1033,2024-04-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,5,1200.0,0.15,Luis Mora
33,1034,2024-04-08,C010,DeltaOps,Norte,Mouse Inalambrico,Perifericos,25,25.0,0.00,Carlos Ruiz
34,1035,2024-04-10,C004,CloudNet,Este,Router WiFi 6,Redes,2,120.0,0.00,Maria Torres
35,1036,2024-04-12,C005,Sistemas Globales,Oeste,Monitor 27,Electronica,4,350.0,0.05,Ana Lopez
36,1037,2024-04-15,C006,NetPrime,Norte,Teclado Mecanico,Perifericos,12,85.0,0.10,Luis Mora
37,1038,2024-04-18,C007,AlphaTech,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz
38,1039,2024-04-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.00,Maria Torres
39,1040,2024-04-22,C008,BetaSoft,Centro,Laptop Pro 15,Electronica,3,1200.0,0.10,Ana Lopez
40,1041,2024-04-25,C009,GammaDevs,Oeste,Mouse Inalambrico,Perifericos,15,25.0,0.00,Luis Mora
41,1042,2024-04-28,C003,DataSolutions,Centro,Router WiFi 6,Redes,5,120.0,0.05,Carlos Ruiz
42,1043,2024-05-01,C010,DeltaOps,Norte,NaN,Electronica,2,350.0,0.05,Maria Torres
43,1044,2024-05-04,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,3,1200.0,0.20,Ana Lopez
44,1045,2024-05-07,C004,CloudNet,Este,SSD 1TB,Almacenamiento,20,95.0,0.10,Luis Mora
45,1046,2024-05-10,C005,Sistemas Globales,Oeste,Teclado Mecanico,Perifericos,6,85.0,0.00,Carlos Ruiz
46,1047,2024-05-12,C006,NetPrime,Norte,Mouse Inalambrico,Perifericos,18,25.0,0.00,Maria Torres
47,1048,2024-05-15,C007,AlphaTech,Sur,Laptop Pro 15,Electronica,-1,1200.0,0.00,Ana Lopez
48,1049,2024-05-18,C002,Innovatek,Sur,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora
49,1050,2024-05-20,C008,BetaSoft,Centro,SSD 1TB,Almacenamiento,25,95.0,0.15,Carlos Ruiz
50,1051,2024-05-22,C009,GammaDevs,Oeste,Monitor 27,Electronica,3,350.0,0.05,Maria Torres
51,1052,2024-05-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.00,Ana Lopez
52,1053,2024-05-28,C010,DeltaOps,Norte,Mouse Inalambrico,Perifericos,20,25.0,0.00,Luis Mora
53,1054,2024-06-01,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,35,95.0,0.20,Carlos Ruiz
54,1055,2024-06-04,C004,CloudNet,Este,Monitor 27,Electronica,5,350.0,0.05,Maria Torres
55,1056,2024-06-07,C005,Sistemas Globales,Oeste,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lopez
56,1057,2024-06-10,C006,NetPrime,Norte,Router WiFi 6,Redes,7,120.0,0.00,Luis Mora
57,1058,2024-06-12,C007,AlphaTech,Sur,Teclado Mecanico,Perifericos,9,85.0,0.05,Carlos Ruiz
58,1059,2024-06-15,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres
59,1060,2024-06-18,C008,BetaSoft,Centro,Monitor 27,Electronica,4,350.0,0.10,Ana Lopez

# 3.1 Carga y exploración del conjunto de datos

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         60 non-null     int64
 1   fecha            60 non-null     datetime64[us]
 2   cliente_id       60 non-null     str
 3   cliente_nombre   60 non-null     str
 4   region           60 non-null     str
 5   producto         59 non-null     str
 6   categoria        60 non-null     str
 7   cantidad         60 non-null     int64
 8   precio_unitario  60 non-null     float64
 9   descuento        60 non-null     float64
 10  vendedor         60 non-null     str
dtypes: datetime64[us](1), float64(2), int64(2), str(6)
memory usage: 5.3 KB

### Observaciones

- El conjunto de datos contiene 60 registros y 11 columnas.

- La columna **fecha** fue cargada correctamente como tipo fecha gracias al parámetro `parse_dates`.

- Se observa un único valor nulo en la columna **producto**, además de un registro con una cantidad negativa, los cuales deberán ser tratados durante la etapa de limpieza.

## 3.2 Limpieza del conjunto de datos

In [6]:
df.isna().sum()

order_id           0
fecha              0
cliente_id         0
cliente_nombre     0
region             0
producto           1
categoria          0
cantidad           0
precio_unitario    0
descuento          0
vendedor           0
dtype: int64

## - Se eliminan los registros

In [7]:
filas_iniciales = len(df)

df = df[df["producto"].notna()]
df = df[df["producto"] != ""]
df = df[df["cantidad"] > 0]

filas_finales = len(df)

print("Registros iniciales:", filas_iniciales)
print("Registros finales:", filas_finales)
print("Registros eliminados:", filas_iniciales - filas_finales)

Registros iniciales: 60
Registros finales: 58
Registros eliminados: 2

### Justificación

- Se eliminaron los registros que presentaban un producto vacío y aquellos con una cantidad menor o igual a cero, ya que representan datos inconsistentes que podrían afectar los resultados del análisis.

- En total se eliminaron **2 registros**.

## 3.3 Creación de nuevas variables

In [9]:
df["ingreso_bruto"] = df["cantidad"] * df["precio_unitario"]

df["ingreso_neto"] = df["ingreso_bruto"] * (1 - df["descuento"])

df["mes"] = df["fecha"].dt.to_period("M")

df.head(60)

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor,ingreso_bruto,ingreso_neto,mes
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lopez,2400.0,2160.00,2024-01
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15,25.0,0.00,Carlos Ruiz,375.0,375.00,2024-01
2,1003,2024-01-10,C003,DataSolutions,Centro,Monitor 27,Electronica,5,350.0,0.05,Ana Lopez,1750.0,1662.50,2024-01
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10,85.0,0.10,Luis Mora,850.0,765.00,2024-01
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3,1200.0,0.15,Carlos Ruiz,3600.0,3060.00,2024-01
5,1006,2024-01-18,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres,1900.0,1900.00,2024-01
6,1007,2024-01-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.05,Ana Lopez,700.0,665.00,2024-01
7,1008,2024-01-22,C006,NetPrime,Norte,Router WiFi 6,Redes,8,120.0,0.00,Luis Mora,960.0,960.00,2024-01
8,1009,2024-01-25,C003,DataSolutions,Centro,SSD 1TB,Almacenamiento,12,95.0,0.10,Maria Torres,1140.0,1026.00,2024-01
9,1010,2024-01-28,C007,AlphaTech,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Carlos Ruiz,1200.0,1200.00,2024-01
10,1011,2024-02-02,C001,TechCorp SA,Norte,Monitor 27,Electronica,4,350.0,0.05,Ana Lopez,1400.0,1330.00,2024-02
11,1012,2024-02-05,C008,BetaSoft,Centro,Mouse Inalambrico,Perifericos,30,25.0,0.05,Maria Torres,750.0,712.50,2024-02
12,1013,2024-02-08,C004,CloudNet,Este,Teclado Mecanico,Perifericos,5,85.0,0.00,Luis Mora,425.0,425.00,2024-02
13,1014,2024-02-10,C009,GammaDevs,Oeste,Router WiFi 6,Redes,3,120.0,0.00,Carlos Ruiz,360.0,360.00,2024-02
14,1015,2024-02-12,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,25,95.0,0.10,Maria Torres,2375.0,2137.50,2024-02
15,1016,2024-02-15,C010,DeltaOps,Norte,Laptop Pro 15,Electronica,2,1200.0,0.20,Ana Lopez,2400.0,1920.00,2024-02
16,1017,2024-02-18,C006,NetPrime,Norte,Monitor 27,Electronica,6,350.0,0.05,Luis Mora,2100.0,1995.00,2024-02
17,1018,2024-02-20,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz,1710.0,1710.00,2024-02
18,1019,2024-02-22,C007,AlphaTech,Sur,Mouse Inalambrico,Perifericos,12,25.0,0.00,Maria Torres,300.0,300.00,2024-02
19,1020,2024-02-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lopez,2400.0,2160.00,2024-02
20,1021,2024-03-01,C008,BetaSoft,Centro,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora,480.0,456.00,2024-03
21,1022,2024-03-04,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,30,95.0,0.15,Carlos Ruiz,2850.0,2422.50,2024-03
22,1023,2024-03-07,C009,GammaDevs,Oeste,Teclado Mecanico,Perifericos,8,85.0,0.00,Maria Torres,680.0,680.00,2024-03
23,1024,2024-03-10,C010,DeltaOps,Norte,Monitor 27,Electronica,3,350.0,0.05,Ana Lopez,1050.0,997.50,2024-03
24,1025,2024-03-12,C004,CloudNet,Este,Laptop Pro 15,Electronica,4,1200.0,0.10,Luis Mora,4800.0,4320.00,2024-03
25,1026,2024-03-15,C005,Sistemas Globales,Oeste,Mouse Inalambrico,Perifericos,20,25.0,0.00,Carlos Ruiz,500.0,500.00,2024-03
26,1027,2024-03-18,C006,NetPrime,Norte,SSD 1TB,Almacenamiento,15,95.0,0.00,Maria Torres,1425.0,1425.00,2024-03
27,1028,2024-03-20,C007,AlphaTech,Sur,Router WiFi 6,Redes,6,120.0,0.10,Ana Lopez,720.0,648.00,2024-03
28,1029,2024-03-22,C002,Innovatek,Sur,Laptop Pro 15,Electronica,1,1200.0,0.00,Luis Mora,1200.0,1200.00,2024-03
29,1030,2024-03-25,C008,BetaSoft,Centro,Teclado Mecanico,Perifericos,10,85.0,0.05,Carlos Ruiz,850.0,807.50,2024-03
30,1031,2024-03-28,C003,DataSolutions,Centro,Monitor 27,Electronica,3,350.0,0.05,Maria Torres,1050.0,997.50,2024-03
31,1032,2024-04-02,C009,GammaDevs,Oeste,SSD 1TB,Almacenamiento,22,95.0,0.10,Ana Lopez,2090.0,1881.00,2024-04
32,1033,2024-04-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,5,1200.0,0.15,Luis Mora,6000.0,5100.00,2024-04
33,1034,2024-04-08,C010,DeltaOps,Norte,Mouse Inalambrico,Perifericos,25,25.0,0.00,Carlos Ruiz,625.0,625.00,2024-04
34,1035,2024-04-10,C004,CloudNet,Este,Router WiFi 6,Redes,2,120.0,0.00,Maria Torres,240.0,240.00,2024-04
35,1036,2024-04-12,C005,Sistemas Globales,Oeste,Monitor 27,Electronica,4,350.0,0.05,Ana Lopez,1400.0,1330.00,2024-04
36,1037,2024-04-15,C006,NetPrime,Norte,Teclado Mecanico,Perifericos,12,85.0,0.10,Luis Mora,1020.0,918.00,2024-04
37,1038,2024-04-18,C007,AlphaTech,Sur,SSD 1TB,Almacenamiento,18,95.0,0.00,Carlos Ruiz,1710.0,1710.00,2024-04
38,1039,2024-04-20,C002,Innovatek,Sur,Monitor 27,Electronica,2,350.0,0.00,Maria Torres,700.0,700.00,2024-04
39,1040,2024-04-22,C008,BetaSoft,Centro,Laptop Pro 15,Electronica,3,1200.0,0.10,Ana Lopez,3600.0,3240.00,2024-04
40,1041,2024-04-25,C009,GammaDevs,Oeste,Mouse Inalambrico,Perifericos,15,25.0,0.00,Luis Mora,375.0,375.00,2024-04
41,1042,2024-04-28,C003,DataSolutions,Centro,Router WiFi 6,Redes,5,120.0,0.05,Carlos Ruiz,600.0,570.00,2024-04
43,1044,2024-05-04,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,3,1200.0,0.20,Ana Lopez,3600.0,2880.00,2024-05
44,1045,2024-05-07,C004,CloudNet,Este,SSD 1TB,Almacenamiento,20,95.0,0.10,Luis Mora,1900.0,1710.00,2024-05
45,1046,2024-05-10,C005,Sistemas Globales,Oeste,Teclado Mecanico,Perifericos,6,85.0,0.00,Carlos Ruiz,510.0,510.00,2024-05
46,1047,2024-05-12,C006,NetPrime,Norte,Mouse Inalambrico,Perifericos,18,25.0,0.00,Maria Torres,450.0,450.00,2024-05
48,1049,2024-05-18,C002,Innovatek,Sur,Router WiFi 6,Redes,4,120.0,0.05,Luis Mora,480.0,456.00,2024-05
49,1050,2024-05-20,C008,BetaSoft,Centro,SSD 1TB,Almacenamiento,25,95.0,0.15,Carlos Ruiz,2375.0,2018.75,2024-05
50,1051,2024-05-22,C009,GammaDevs,Oeste,Monitor 27,Electronica,3,350.0,0.05,Maria Torres,1050.0,997.50,2024-05
51,1052,2024-05-25,C003,DataSolutions,Centro,Laptop Pro 15,Electronica,2,1200.0,0.00,Ana Lopez,2400.0,2400.00,2024-05
52,1053,2024-05-28,C010,DeltaOps,Norte,Mouse Inalambrico,Perifericos,20,25.0,0.00,Luis Mora,500.0,500.00,2024-05
53,1054,2024-06-01,C001,TechCorp SA,Norte,SSD 1TB,Almacenamiento,35,95.0,0.20,Carlos Ruiz,3325.0,2660.00,2024-06
54,1055,2024-06-04,C004,CloudNet,Este,Monitor 27,Electronica,5,350.0,0.05,Maria Torres,1750.0,1662.50,2024-06
55,1056,2024-06-07,C005,Sistemas Globales,Oeste,Laptop Pro 15,Electronica,2,1200.0,0.10,Ana Lopez,2400.0,2160.00,2024-06
56,1057,2024-06-10,C006,NetPrime,Norte,Router WiFi 6,Redes,7,120.0,0.00,Luis Mora,840.0,840.00,2024-06
57,1058,2024-06-12,C007,AlphaTech,Sur,Teclado Mecanico,Perifericos,9,85.0,0.05,Carlos Ruiz,765.0,726.75,2024-06
58,1059,2024-06-15,C002,Innovatek,Sur,SSD 1TB,Almacenamiento,20,95.0,0.00,Maria Torres,1900.0,1900.00,2024-06
59,1060,2024-06-18,C008,BetaSoft,Centro,Monitor 27,Electronica,4,350.0,0.10,Ana Lopez,1400.0,1260.00,2024-06

## Resumen mensual

In [10]:
resumen = df.groupby("mes").agg(
    total=("ingreso_neto", "sum"),
    numero_ventas=("order_id", "count")
)

resumen

            total  numero_ventas
mes
2024-01  13773.50             10
2024-02  13050.00             10
2024-03  14454.00             11
2024-04  16689.00             11
2024-05  11922.25              9
2024-06  11209.25              7

## - Se crea la tabla de metas

In [11]:
metas = pd.DataFrame({
    "mes": [
        "2024-01",
        "2024-02",
        "2024-03",
        "2024-04",
        "2024-05",
        "2024-06"
    ],
    "meta": [
        15000,
        15000,
        15000,
        15000,
        15000,
        15000
    ]
})

metas["mes"] = pd.PeriodIndex(metas["mes"], freq="M")

metas

       mes   meta
0  2024-01  15000
1  2024-02  15000
2  2024-03  15000
3  2024-04  15000
4  2024-05  15000
5  2024-06  15000

## 3.4 Comparación con las metas

In [12]:
resumen = resumen.reset_index()

resumen = resumen.merge(
    metas,
    on="mes",
    how="left"
)

resumen

       mes     total  numero_ventas   meta
0  2024-01  13773.50             10  15000
1  2024-02  13050.00             10  15000
2  2024-03  14454.00             11  15000
3  2024-04  16689.00             11  15000
4  2024-05  11922.25              9  15000
5  2024-06  11209.25              7  15000

## - Calculo Porcentaje de cumplimiento

In [13]:
resumen["cumplimiento"] = (
    resumen["total"] / resumen["meta"]
) * 100

resumen

       mes     total  numero_ventas   meta  cumplimiento
0  2024-01  13773.50             10  15000     91.823333
1  2024-02  13050.00             10  15000     87.000000
2  2024-03  14454.00             11  15000     96.360000
3  2024-04  16689.00             11  15000    111.260000
4  2024-05  11922.25              9  15000     79.481667
5  2024-06  11209.25              7  15000     74.728333

## 3.5 Exportar la información

In [15]:
# Se converierte la columna mes a texto
df["mes"] = df["mes"].astype(str)

# Se crea la base de datos
engine = create_engine("sqlite:///../output/techventas.db")

# Finalmente se debe Exportar
df.to_sql(
    "ventas",
    engine,
    if_exists="replace",
    index=False
)

58

## -Se verifica la información

In [16]:
pd.read_sql(
    "SELECT COUNT(*) FROM ventas",
    engine
)

   COUNT(*)
0        58

## Conclusión

Durante esta actividad se utilizó Pandas para preparar el conjunto de datos antes de su análisis. Se identificaron y eliminaron registros con información inconsistente, se crearon nuevas variables para calcular los ingresos y se realizó un resumen mensual de las ventas. Finalmente, los datos fueron exportados a una base de datos SQLite para facilitar su consulta en etapas posteriores.

Este ejercicio me permitió comprender la importancia de la limpieza y transformación de los datos, ya que una buena preparación ayuda a obtener resultados más confiables y facilita el análisis posterior.